id: P000113
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ཟབ་མོ་སྙིང་ཐིག་གི་གནད་ཐམས་ཅད་བསྡུས་པའི་དོན་ཁྲིད་ལག་ལེན་གསལ་བ་བཞུགས་སོ།།
  authors:
  - མཛད་པ་པོ། བཀྲ་ཤིས་རྒྱ་མཚོ།
  layers:
  - book_title
  - author
  id: SHE-RTD-025
web_metadata:
  title:
    en: A Clear Explanation of the Essential Meaning of the Profound Heart Essence
    bo: ཟབ་མོ་སྙིང་ཐིག་གི་གནད་ཐམས་ཅད་བསྡུས་པའི་དོན་ཁྲིད་ལག་ལེན་གསལ་བ་བཞུགས་སོ།
  collection:
    en: Treasury of Precious Termas–  Book 25
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༢༥
  author:
    en: Tashi Gyatso
    bo: བཀྲ་ཤིས་རྒྱ་མཚོ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-025
  category:
    en: Dzogchen
    bo: རྫོགས་ཆེན།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-025.epub
  description:
    en: ''
    bo: ''
